# Generated by Django 3.1.6 on 2021-06-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollParty', '0003_auto_20210531_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
